### ISSUE TITLE
Permission to use code base for an open source project.

### ISSUE THREAD

**Issue by Krunniee** [FCCouncil/Moonglow#110]
I, redacted hereby ask for permission to use the entire code base for an open source project of mine. Please see below for the links as one is the organization link and the other is the repository link. However, the license of the project is under an MIT

**Links:**
[Organization Link](https://github.com/FLCommunity)
[Repository Link](https://github.com/FLCommunity/Moonlight)

**Comment by mattsilver1** [comment]
Sure, feel free to.

**Comment by Krunniee** [comment]
Thank you, mind merging my recent pull request?
