### ISSUE TITLE
s?kick 2 minute delay on members

### ISSUE THREAD

**Issue by HardLadJosh** [FCCouncil/Moonglow#37]
**Discord Information**
Discord Username with Discriminator: - ̗̀Josн ̖́-#2000
If you can provide, what is your user ID: 273035913725214720
What is your role in the Fortnite Community server: Member

**Describe the bug**
the command s?kick takes over 2 minutes to perform
**To Reproduce**
1)
2)
3)
4)
5)
6)
...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mattsilver1** [comment]
Thank you for your issue, our Development Team will look into this issue and will provide you additional information here.

**Comment by HardLadJosh** [comment]
I just tried it again on a bot and doesn't seem to work at all :/

**Comment by mattsilver1** [comment]
Command has been temporarily disabled while we look for a fix.

**Comment by mattsilver1** [comment]
#41 has fixed this issue.
