### ISSUE TITLE
Game command not functioning properly

### ISSUE THREAD

**Issue by TheSkele27** [FCCouncil/Moonglow#53]
**Discord Information**
Discord Username with Discriminator:
If you can provide, what is your user ID:TheSkele27#1337
What is your role in the Fortnite Community server:

**Describe the bug**
The date started shows as 1970.
**To Reproduce**
1)s?game
2)
3)
4)
5)
6)
...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CoalSephos** [comment]
thats not the ?whois command is it

**Comment by TheSkele27** [comment]
smh lmao, fixed it ;-;

**Comment by TheSkele27** [comment]
Issue has been solved.
