### ISSUE TITLE
Suggestions by yologamerXD2Comeback#3434

### ISSUE THREAD

**Issue by yolothePro** [FCCouncil/Moonglow#70]
**Discord Username with Discriminator:**yologamerXD2Comeback#3434

**Suggestions:** Being able to customize your welcome message,leave message. Also add some type of logs(For edited-deleted messages), I think also a dashboard should make the bot really cool🙄

**Comment by Krunniee** [comment]
Use a database such as `enmap-sqlite` or level db

**Comment by mattsilver1** [comment]
You are now able to customize your guild specific settings, and logs will be coming soon.
Thanks for the suggestion!
