### ISSUE TITLE
Delete eping.js 

### ISSUE THREAD

**Issue by mattsilver1** [FCCouncil/Moonglow#91]
**Discord Information**
Discord Username with Discriminator: Matthew#0008
If you can provide, what is your user ID:
What is your role in the Fortnite Community server: Fortnite Community Development Team

**Describe the bug**
Delete `eping.js` since it's deprecated and no longer in use.

**To Reproduce**
1)
2)
3)
4)
5)
6)
...

**Expected behavior**

**Screenshots**

**Additional context**
https://github.com/FCCouncil/Moonglow/blob/master/commands/eping.js

**Comment by Blasphemouse** [comment]
Looks like it was removed here:
https://github.com/FCCouncil/Moonglow/commit/1e44aa90b81b64e58d56d98bd0880804d44dcfb0

**Comment by mattsilver1** [comment]
Apologies, forgot to close this issue after I merged the Pull Request.
